version: '1.0'
stages:
 - prepare
 - build
 - test
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'harishkalyanpur/cf-example-python-django'
    revision: master
    git: github
  build_my_image:
    title: Building Docker Image
    stage: build
    type: build
    image_name: my-django-image
    working_directory: ./
    tag: master
    dockerfile: Dockerfile
    disable_push: true
  push_to_my_registry:
    stage: 'build'
    type: push
    title: Pushing to a registry
    candidate: ${{build_my_image}}
    tag: 'v1.0.0'
    registry: dockerhubHK
    image_name: harishkalyanpur/my-django-image
  test_my_image:
     title: Running unit tests
     stage: test
     image: '${{build_my_image}}'
     commands:
       - python -m unittest composeexample.utils
